config/routes.rb
Thebigshake::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  resources :bands, only: [:show, :update]

  get 'project', to: 'home#project'
  get 'team', to: 'home#team'
  get 'comments', to: 'home#comments'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/band.rb
class Band < ActiveRecord::Base

  rails_admin do
    list do
      sort_by :play_count
      field :name
      field :play_count do
        sort_reverse true
      end
    end
    edit do
      field :name
      field :track_id
      field :track_name
      field :bio
      field :thumbnail
      field :picture
      field :facebook
      field :twitter
      field :link
    end
  end

  if Rails.env.development?
    has_attached_file :picture
    has_attached_file :thumbnail
  else
    has_attached_file :picture, storage: :s3,
      s3_credentials: Rails.root.join("config", "s3.yml"),
      path: "/bands/:id/picture/:filename",
      url: ":s3_eu_url"
    has_attached_file :thumbnail, storage: :s3,
      s3_credentials: Rails.root.join("config", "s3.yml"),
      path: "/bands/:id/thumbnail/:filename",
      url: ":s3_eu_url"
  end

  validates :name, presence: true

  acts_as_url :name

  def to_param
    url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :get_bands

  def get_bands
    @bands = Band.all
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def show
    @band = Band.find_by(url: params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.increment(:play_count, 1).save
    render nothing: true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def project
  end

  def team
    @team = YAML::load(File.open(Rails.root.join('config', 'team.yml')))
  end

  def comments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown content
    return '' unless content
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    md.render(content).html_safe
  end
end

app/views/bands/show.haml
#main

  %figure
    = image_tag @band.picture.url

  %article
    %h2= @band.name
    .bio
      = markdown @band.bio
    .links
      - if @band.facebook?
        = link_to @band.facebook do
          %i.icon-facebook
      - if @band.twitter?
        = link_to @band.twitter do
          %i.icon-twitter
      - if @band.link?
        = link_to @band.link do
          %i.icon-music

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45837235-1', 'thebigshake.net');
  ga('send', 'pageview');

app/views/home/comments.haml
#main
  %figure
    = image_tag 'project_1.png', alt: 'The Big Shake', title: 'The Big Shake'
    = image_tag 'project_2.png', alt: 'The Big Shake', title: 'The Big Shake'
    = image_tag 'project_3.png', alt: 'The Big Shake', title: 'The Big Shake'
  %article#team
    %h2 Vos réactions
    .fb-comments{data: {href: "http://thebigshake.net", numposts: "10", width: '600px'}}

app/views/home/index.haml
#picker
  %ul
    - @bands.each_with_index do |band, ii|
      %li.band{data: {track_id: band.track_id, band_id: band.id}}
        %figure{style: "background-image: url(#{band.thumbnail.url})"}
          .icon
            %i.icon-play
          .veil
        .name
          %h5= band.name
          %h6= band.track_name
        .clear
  -#%button#pause PAUSE
  .clear
#player
  %h3#hint 
    1 court-métrage, 11 groupes. Choisissez parmi ces 11 BO possibles.
  %iframe#tbs-player{src: 'http://player.vimeo.com/video/72523306?api=1&player_id=tbs-player&byline=0&title=0', width: '780px', height: '439px', frameborder: '0', webkitAllowFullScreen: true, mozallowfullscreen: true, allowFullScreen: true }
  %br
  .fb-like{data: {href: 'https://www.facebook.com/thebigshakefilm', layout: 'button_count', action: 'like', show_faces: 'false', share: 'false'}}
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45837235-1', 'thebigshake.net');
  ga('send', 'pageview');

app/views/home/project.haml
#main
  %figure
    = image_tag 'project_1.png', alt: 'The Big Shake', title: 'The Big Shake'
    = image_tag 'project_2.png', alt: 'The Big Shake', title: 'The Big Shake'
    = image_tag 'project_3.png', alt: 'The Big Shake', title: 'The Big Shake'
  %article
    %h2 Le projet
    .bio
      %p
        %em
          « Il est là, sur le rebord. Le geste quotidien qui me fait femme. Je l’exécute. Je l’exécute comme dans les publicités dans lesquelles les filles qui se rasent n’ont pas de poils à raser, en faisant des pointes avec mes doigts de pieds, tout en sensualité. Et, je dérape. Un minuscule point rouge, presque noir, apparaît et j’ai l’habitude. J’ai l’habitude de ce sang là. Mais, il y a les images, les images qui vont plus loin, qui vont plus loin que les gestes, qui surgissent comme des flashs et envahissent. Elles sont là, elles viennent se calquer aux gestes quotidiens, aux échanges les plus simples, aux visages les plus familiers, ces images de l’horreur, de la mort. Et parfois, elles prennent le pas sur le geste. »
      %p
        Pendant la guerre du Vietnam, Martin Scorsese tourne un film court de 5’ intitulé The Big shave. Un homme dans une salle de bain se rase le visage jusqu’au sang, jusqu’à la mort. Le film est un cri poussé contre la violence de la guerre et de l’obligation de partir au front, de l’injonction à la violence. Cette première violence, c’est celle de se ressembler tous, en se rasant le crane, la barbe et de revêtir l’uniforme.
      %p
        The big shake de Lucie Rico est une relecture du film de Scorsese. A ceci près que c’est une femme qui exécute le geste quotidien du rasage. Jamais l’on a remis en cause cet acte qui fait d’une femme, une femme, être imberbe, pourtant, il porte en lui sa violence. La lame s’immisce plus loin qu’à fleur de peau, elle tranche le flux des pensées et, par la peur, y inscrit des images de coupure, de sang et de mort. 
      %p
        Si l’on peut voir ici un geste féministe, comme on voyait dans le film de Scorsese un film militant, le film est avant tout une image de la peur, qu’il fallait sortir de soi pour la dompter, qu’il fallait partager, s’approprier. Nous sommes les observateurs de la pulsion qui s'exprime tout au long d'une hallucination visuelle puissante. 
      %p
        La caméra garde une distance clinique avec ce tableau animé, lente observation du passage du blanc au rouge.
      %p
        En proposant aux spectateurs de choisir le son sur l’image, Lucie Rico propose de faire cohabiter les multiples présents dans l'interprétation d'images. Elle met face les spectateurs aux images, les obligeant à se les approprier, à jouer avec leurs peurs et à participer à cette imperturbable scène d'autodestruction, en lui donnant le sens, la rythmique et le degré de violence qu'ils souhaitent : d'une distance  à un discours univoque sur les images.
      %p
        Marine Louvet
      %p Contact : rico.lucie@gmail.com
      .fb-like{data: {href: 'https://www.facebook.com/thebigshakefilm', layout: 'button_count', action: 'like', show_faces: 'false', share: 'false'}}

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45837235-1', 'thebigshake.net');
  ga('send', 'pageview');

app/views/home/team.haml
#main
  %figure
    &nbsp;
  %article#team
    %h2 L'équipe du film
    %ul
      - @team.each do |member|
        %li
          = link_to member['name'], "##{member['slug']}"
          %span.role
            ·
            = member['role']

    - @team.each do |member|
      %h3
        %a{id: member['slug']}= member['name']
        %p.role= member['role']
      .bio
        %p= member['bio']
      %p.team-links
        - if member['website']
          = link_to member['website']['url'], target: :new, class: 'website' do
            %i.icon-globe
            = member['website']['name']
        - if member['facebook']
          = link_to member['facebook']['url'], target: :new, class: 'facebook' do
            %i.icon-facebook-sign
            = member['facebook']['name']
        - if member['twitter']
          = link_to member['twitter']['url'], target: :new, class: 'twitter' do
            %i.icon-twitter-sign
            = member['twitter']['name']
        - if member['googleplus']
          = link_to member['googleplus']['url'], target: :new, class: 'googleplus' do
            %i.icon-google-plus-sign
            = member['googleplus']['name']

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title The Big Shake
    %script{src: '//connect.soundcloud.com/sdk.js'}
    %link{href: 'http://fonts.googleapis.com/css?family=Oswald:300,400,700', rel: 'stylesheet', type: 'text/css'}
    %meta{property: 'og:title', content: "The Big Shake"}
    %meta{property: 'og:url', content: 'http://thebigshake.net'}
    %meta{property: 'og:type', content: 'website'}
    %meta{property: 'og:image', content: "#{root_url}/fb_preview.jpg"}
    %meta{property: 'fb:app_id', content: '725460550815345'}
    %meta{property: 'fb:admins', content: '677501914'}
    %meta{property: 'fb:admins', content: '546857582'}
    -#%meta{property: 'og:video', content: 'http://vimeo.com/72523306'}
    %meta{property: 'og:description', content: 'Relecture du film de Scorsese, The Big Shake met en scène une jeune femme confrontée en apparence à un geste du quotidien qui dérape.'}
    %meta{name: 'description', content: 'Relecture du film de Scorsese, The Big Shake met en scène une jeune femme confrontée en apparence à un geste du quotidien qui dérape.'}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=725460550815345";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
%body
  .fb-root
  %header
    #left
      %h1= link_to 'THE BIG SHAKE', root_path
    #right
      %ul#menu
        %li= link_to 'LES RÉACTIONS', comments_path
        %li= link_to "L'EQUIPE", team_path
        %li.bands
          = link_to 'LES GROUPES', 'javascript://'
          %ul.dropdown
            - @bands.each do |band|
              %li
                = link_to band.name, band
        %li 
          = link_to 'LE PROJET', project_path
    .clear
  = yield
  .clear
  %footer